# Copyright (C) 2015 Raphaël Poggi. All rights reserved.
# Author: Raphaël Poggi <poggi.raph@gmail.com>
#
# Provided under the three clause BSD license found in the LICENSE file.

extra-$(CONFIG_STM32F401) := stm32f401.lds
extra-$(CONFIG_STM32F407) += stm32f407.lds
extra-$(CONFIG_STM32F429) += stm32f429.lds
extra-$(CONFIG_STM32F746) += stm32f746.lds
