# Copyright (C) 2015 Raphaël Poggi. All rights reserved.
# Author: Raphaël Poggi <poggi.raph@gmail.com>
#
# Provided under the three clause BSD license found in the LICENSE file.

obj-$(CONFIG_STM32F401) := boot-stm32f401.o
obj-$(CONFIG_STM32F407) := boot-stm32f407.o
obj-$(CONFIG_STM32F429) := boot-stm32f429.o
obj-$(CONFIG_STM32F746) := boot-stm32f746.o
