# Copyright (C) 2015 Raphaël Poggi. All rights reserved.
# Author: Raphaël Poggi <poggi.raph@gmail.com>
#
# Provided under the three clause BSD license found in the LICENSE file.

obj-$(CONFIG_AT91SAMA5D3) := sama5d3.o
obj-y += aic-at91.o
obj-y += pmc-at91.o
