# Copyright (C) 2015 Raphaël Poggi. All rights reserved.
# Author: Raphaël Poggi <poggi.raph@gmail.com>
#
# Provided under the three clause BSD license found in the LICENSE file.

subdirs-$(CONFIG_CPU_ARMV7M) += armv7m
subdirs-y += dts
subdirs-y += lib
