# Copyright (C) 2015 Raphaël Poggi. All rights reserved.
# Author: Raphaël Poggi <poggi.raph@gmail.com>
#
# Provided under the three clause BSD license found in the LICENSE file.

obj-y := rcc-stm32.o
obj-$(CONFIG_STM32F401) += stm32f401.o
obj-$(CONFIG_STM32F407) += stm32f407.o
obj-$(CONFIG_STM32F429) += stm32f429.o
obj-$(CONFIG_STM32F746) += stm32f746.o
obj-y += usart-stm32.o
obj-y += pio-stm32.o
obj-y += timer-stm32.o
obj-y += i2c-stm32.o
obj-y += spi-stm32.o
obj-y += dma-stm32.o
obj-$(CONFIG_STM32F429) += ltdc-stm32.o
obj-$(CONFIG_STM32F429) += fmc-stm32.o
obj-$(CONFIG_STM32F746) += ltdc-stm32.o
obj-$(CONFIG_STM32F746) += fmc-stm32.o
obj-$(CONFIG_IRQ_SUBSYS) += exti-stm32.o
obj-y += flash-stm32.o
