# Copyright (C) 2015 Raphaël Poggi. All rights reserved.
# Author: Raphaël Poggi <poggi.raph@gmail.com>
#
# Provided under the three clause BSD license found in the LICENSE file.

obj-y := rcc-stm32.o
obj-$(CONFIG_STM32F407) += stm32f407.o
obj-$(CONFIG_STM32F429) += stm32f429.o
obj-y += usart-stm32.o
obj-y += pio-stm32.o
obj-y += timer-stm32.o
obj-y += i2c-stm32.o
obj-y += spi-stm32.o
obj-y += dma-stm32.o
obj-y += ltdc-stm32.o
obj-y += fmc-stm32.o
obj-y += exti-stm32.o
