# Copyright (C) 2015 Raphaël Poggi. All rights reserved.
# Author: Raphaël Poggi <poggi.raph@gmail.com>
#
# Provided under the three clause BSD license found in the LICENSE file.

obj-y := main.o
obj-y += mutex.o
obj-y += scheduler.o
obj-y += semaphore.o
obj-y += queue.o
obj-y += thread.o
obj-y += time.o
