# Copyright (C) 2015 Raphaël Poggi. All rights reserved.
# Author: Raphaël Poggi <poggi.raph@gmail.com>
#
# Provided under the three clause BSD license found in the LICENSE file.

obj-y := main.o
obj-y += kmutex.o
obj-y += scheduler.o
obj-y += ksem.o
obj-y += syscall.o
obj-y += queue.o
obj-y += thread.o
obj-y += ktime.o
