# Copyright (C) 2015 Raphaël Poggi. All rights reserved.
# Author: Raphaël Poggi <poggi.raph@gmail.com>
#
# Provided under the three clause BSD license found in the LICENSE file.

subdirs-$(CONFIG_MACH_QEMU) += mach-qemu
subdirs-$(CONFIG_MACH_STM32) += mach-stm32
