# Copyright (C) 2015 Raphaël Poggi. All rights reserved.
# Author: Raphaël Poggi <poggi.raph@gmail.com>
#
# Provided under the three clause BSD license found in the LICENSE file.

obj-y += stdio.o
obj-y += string.o
obj-y += unistd.o
obj-y += pthread.o
obj-y += semaphore.o
obj-y += time.o
