# Copyright (C) 2015 Raphaël Poggi. All rights reserved.
# Author: Raphaël Poggi <poggi.raph@gmail.com>
#
# Provided under the three clause BSD license found in the LICENSE file.

obj-y := device.o
obj-y += clk.o
obj-y += pio.o
obj-y += usart.o
obj-y += timer.o
obj-y += i2c.o
obj-y += spi.o
obj-y += dma.o
obj-y += mtd.o
obj-$(CONFIG_STM32F429) += lcd.o
obj-$(CONFIG_STM32F429) += ili9341.o
