# Copyright (C) 2015 Raphaël Poggi. All rights reserved.
# Author: Raphaël Poggi <poggi.raph@gmail.com>
#
# Provided under the three clause BSD license found in the LICENSE file.

obj-y := svc_asm.o
obj-y := svc.o
obj-y += syscall.o
obj-y += interrupt.o
obj-y += thread.o
