# Copyright (C) 2015 Raphaël Poggi. All rights reserved.
# Author: Raphaël Poggi <poggi.raph@gmail.com>
#
# Provided under the three clause BSD license found in the LICENSE file.

obj-$(CONFIG_STM32F407) += stm3240g_eval.o
obj-$(CONFIG_STM32F429) += lpd.o
obj-$(CONFIG_STM32F401) += stm32f401_dev.o
