dtb-$(CONFIG_STM32F407) += stm3240g_eval.o
dtb-$(CONFIG_STM32F429) += lpd.o
dtb-$(CONFIG_STM32F401) += stm32f401_dev.o
dtb-$(CONFIG_STM32L443) += eclipse.o
dtb-$(CONFIG_STM32L476) += nucleo_l476.o
dtb-$(CONFIG_STM32L442) += mx_tracker.o
obj-y += rnk_dtb.o
