# Copyright (C) 2016 Raphaël Poggi. All rights reserved.
# Author: Raphaël Poggi <poggi.raph@gmail.com>
#
# Provided under the three clause BSD license found in the LICENSE file.

obj-y := asm.o
obj-y += context.o
obj-y += exceptions.o
obj-y += interrupts.o
obj-y += spinlock.o
obj-y += svc.o
