subdirs-$(CONFIG_TEST_MTD) := mtd_tests
subdirs-$(CONFIG_TEST_MUTEX) += mutex_tests
subdirs-$(CONFIG_TEST_QUEUE) += queue_tests
subdirs-$(CONFIG_TEST_SEM) += sem_tests
subdirs-$(CONFIG_TEST_SYSCALL) += syscall_tests
subdirs-$(CONFIG_TEST_THREAD) += thread_tests
subdirs-$(CONFIG_TEST_TIMER) += timer_tests
subdirs-$(CONFIG_TEST_TICKLESS) += tickless_tests
